#!/bin/bash
#SBATCH --ntasks=[PROCESSORS_PER_NODE]
#SBATCH --nodes=[NUMBER_OF_NODES]
#SBATCH --partition=[QUEUE]
#SBATCH --time=[HOURS]:[MINUTES]:[SECONDS]
#SBATCH --account=[DEPARTMENT]
#SBATCH --job-name=[JOB_NAME]
#SBATCH --mail-user=%{USER}@memphis.edu
#SBATCH --mail-type=[MAIL_OPTIONS]
#SBATCH --mem=[MEMORY_NEEDED_FOR_JOB]
#SBATCH --mem-per-cpu=[PER_PROCESS_MEMORY_NEEDED_FOR_JOB]
#SBATCH --output=[OUTPUT_FILE]
#SBATCH --error=[ERROR_FILE]
#SBATCH --array=[ARRAYLENGTH]
 
cd $SLURM_SUBMIT_DIR
 
module load [MODULE]
 
echo "$SLURM_JOB_ID"
echo "$SLURM_ARRAY_JOB_ID"
echo "$SLURM_JOB_NODELIST"
 
/PATH/TO/PROGRAM [PROGRAM_SWITCHES]